### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#106]
Create docs for the scripts in data storehouse

**Comment by Ayushlion8** [comment]
Hey, I would like to work on this issue:)

**Comment by neokd** [comment]
@Ayushlion8 work on one issue at a time

**Comment by Salonikansal2** [comment]
please assign

**Comment by harshita1611** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by neokd** [comment]
@harshita1611 Yeah sure

**Comment by harshita1611** [comment]
I have put a pr you may review and let me know the changes

**Comment by harshita1611** [comment]
please let me know after you merged
