### ISSUE TITLE
Add New Datasets

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#117]
## Description
This issue is for adding new datasets which are not present in datastorehouse and for future use

**Comment by Titanpimpale** [comment]
Hey @neokd I can add a **_dataset_** of 

1. Most Popular Github Repositories, 
2. Amazon Products Dataset 2023, 
3. Sports Shoes Brands,
4. Economic growth and unemployment rate,
5. Football Competitions Dataset

 and many more please **assign** it to me

**Comment by neokd** [comment]
@Titanpimpale any updates?

**Comment by Titanpimpale** [comment]
Yes I have updated datashores with various dataset please accepts my pull request and if possible put hacktoberfest tags🙏

**Comment by neokd** [comment]
Can u refer the issue where you have created the PR

**Comment by MercMayhem** [comment]
@neokd I have created a pull request for player stats in a valorant esports tournament under the entertainment directory.

**Comment by neokd** [comment]
@MercMayhem  this issue is open for everyone who wants to add an dataset
