### ISSUE TITLE
Datasets for LLM's

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#125]
## Description
Add datasets that can be used to fine tune LLM. This issue is open for any type of dataset for respective LLM's (LLAMA2, MISTRAL,etc)

## Expected Behaviour
The dataset should be large in size and should follow formats for respective LLM's

**Comment by VigneshRamanathan101** [comment]
@neokd do we need our own dataset or can we refer external data sets.


I find some external dataset from Kaggle and other sources

**Comment by neokd** [comment]
We can have from external sources too.

**Comment by VigneshRamanathan101** [comment]
> We can have from external sources too. 

I have a few external links how do want me to add them

1. Add a readme in new folder /Datastore/StoreHouse/LLM  And put all the references in them
2. Download and add them to this repo (which could make our repo larger and also maybe has some licensing conflicts)


I would suggest the 1st approach

**Comment by neokd** [comment]
Share in this issue we'll check and add them to the repo

**Comment by VigneshRamanathan101** [comment]
https://huggingface.co/datasets/Hello-SimpleAI/HC3
https://huggingface.co/datasets/MohamedRashad/ChatGPT-prompts/blob/main/train.csv
https://github.com/Zjh-819/LLMDataHub - this is github repo with large LLM datasets.
https://www.kaggle.com/datasets/radek1/additional-train-data-for-llm-science-exam

**Comment by VigneshRamanathan101** [comment]
Can you assign it to me and close the issue?

**Comment by VigneshRamanathan101** [comment]
@neokd cam we close this issue or do we need Anything more.

**Comment by neokd** [comment]
> https://huggingface.co/datasets/Hello-SimpleAI/HC3

You can add it as an readme or some file referencing the links something similar to https://github.com/Zjh-819/LLMDataHub this repo which u shared

**Comment by VigneshRamanathan101** [comment]
Sure @neokd . I will create the readme.

**Comment by VigneshRamanathan101** [comment]
Created a new PR for this issue
