### ISSUE TITLE
Create Scrapper to scrape gutenberg 

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#29]

**Comment by vigneshRamanathan3105** [comment]
Is it still active and not completed?

If so I would like to contribute

**Comment by neokd** [comment]
Yes it is still active @vigneshRamanathan3105 u can create a new python script in the scripts folder.

**Comment by vigneshRamanathan3105** [comment]
@neokd   Please assigne this to me and I would like to know more details on it.

**Comment by neokd** [comment]
Done!

**Comment by vigneshRamanathan3105** [comment]
@neokd should I create a web scrapper to scrape https://www.gutenberg.org/ ?

What are the requirements ?

**Comment by neokd** [comment]
Yes u need to make a scrapper to get all the books from Gutenberg website and store in JSON format as Title of book , author name and  book content

**Comment by neokd** [comment]
@vigneshRamanathan3105 are you working on it?

**Comment by vigneshRamanathan3105** [comment]
Yea @neokd
