### ISSUE TITLE
Create a python file for Zipping large files 

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#33]
Make a script to zip large JSON/CSV files the script must contain common zipping algorithms.

**Comment by saakshiraut28** [comment]
Hey @neokd, I would like to contribute to this issue. 

Plus, I had a question regarding the same:

1. After creating the script, do we have to add it to the `DataStorehouse/script/` directory?

**Comment by neokd** [comment]
@saakshiraut28 Yes you can work on this issue and you need to put it in DataStorehouse/script/ folder

**Comment by neokd** [comment]
@saakshiraut28 Any updates?

**Comment by saakshiraut28** [comment]
@neokd I'm still working on it.

I had a query, whether I have to create a script that will automatically compress all the files in the [DataStorehouse](https://github.com/neokd/DataStorehouse/tree/main)/[StoreHouse](https://github.com/neokd/DataStorehouse/tree/main/StoreHouse) folder?

**Comment by neokd** [comment]
No, when given a file it should compress in a desired format based on user input , the script should get zip format and unzipped file/folder from the user and place the zipped version in the same folder as the input file/folder.
