### ISSUE TITLE
Update README.md to show Contributors

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#36]
Update the readme to show contributors who contributed to the repo (only their profile picture)

**Comment by rtiop** [comment]
May I be assigned this issue? Should I include myself?

**Comment by neokd** [comment]
@rtiop Since it's a easy one you can work on it but focus on one issue at a time

**Comment by neokd** [comment]
we were thinking of something like this and it should update automatically for reference u can see [here](https://levelup.gitconnected.com/displaying-contributors-image-on-readme-files-with-no-pain-f1cbaca963e8#:~:text=All%20you%20have%20to%20do%20is%20navigate%20to%20contributors%2Dimg,the%20URL%20as%20shown%20below.&text=Or%20you%20can%20also%20use,Well%2C%20there%20you%20go.)

**Comment by rtiop** [comment]
You can actually directly use contrib.rocks to find an image with the contributors. They provide a link you can paste directly into the README that leads to their website. From there they manage all the low-level details and hand you back an image like the one I adjoint.
<img width="363" alt="Screenshot 2023-07-05 at 15 20 08" src="https://github.com/neokd/DataStorehouse/assets/101009997/808352aa-d311-431b-b570-6421908ae396">
That should do the job. Should I  just paste the link into the README and create a pull request? It should do the job, at least while contrib.rocks keeps working.

**Comment by neokd** [comment]
yes,u can use that

**Comment by rtiop** [comment]
For future reference: this does update, but not automatically, only once in a while. So if it doesn't immediately display a new contributor, just wait a bit (maybe up to a day).
