### ISSUE TITLE
Create a Readme to run the website locally 

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#38]
## Description
A Readme file for users to start with website and run it locally 

## Expected Behavior
A readme for users to run project locally. File to be placed inside the website folder of the repository

## Current Behavior
No Readme 

## Steps to Reproduce (if applicable)
Create a README.md file in Website folder

**Comment by Ankit8848** [comment]
hey, I  would like to work in it . could you please assign to me . @neokd

**Comment by neokd** [comment]
Yeah sure u can work on it

**Comment by Ankit8848** [comment]
I just have to create Readme file and all steps required to run locally then I can do it . Thanks for assigning. @neokd

**Comment by Bchass** [comment]
@Ankit8848 Any update on this? I'm interested in running the website locally.

**Comment by Ankit8848** [comment]
@Bchass if you want, you can work on it.

**Comment by neokd** [comment]
@Ankit8848 any updates on the README file?

**Comment by Bchass** [comment]
> @Ankit8848 any updates on the README file?

You can assign this to me. I'll work on it later tonight.

**Comment by Bchass** [comment]
Created a PR: https://github.com/neokd/DataStorehouse/pull/82

**Comment by neokd** [comment]
Thanks for your contribution
