### ISSUE TITLE
Favicon needed for the website (not urgent)

### ISSUE THREAD

**Issue by rtiop** [neokd/DataStorehouse#41]
## Description

The website currently displays the default globe favicon. It would be preferable if a unique favicon (which could later be used as a logo) was displayed.

## Requirements

1.  Create an icon file (.ICO, .PNG or other) and put it in the website folder, maybe in a new 'assets' folder.
2. Modify the HTML pages to include the icon on all pages. [Here's how to](https://www.w3schools.com/html/html_favicon.asp)
3. Submit a pull request and see if @neokd approves it.

## Skills needed

1. Creating logos
2. Basic HTML skills

## Note
Take a look at the website before starting, matching its visual identity (orange) would be better.

**Comment by rtiop** [comment]
How do I had labels to this issue. The sidebar on the right doesn't seem to be interactive.

**Comment by rtiop** [comment]
* How do I add labels to this issue?

**Comment by neokd** [comment]
what label u want to add?

**Comment by rtiop** [comment]
Ok. Thanks. 🙏

**Comment by ujju2000** [comment]
Added the favicon, submitted the pull request

**Comment by neokd** [comment]
Thanks for your contribution ❤️
