### ISSUE TITLE
Fix Gudenberg json

### ISSUE THREAD

**Issue by vigneshRamanathan3105** [neokd/DataStorehouse#55]
## Description
Fix gudenberg JSON 

## Expected Behavior
gudenberg JSON a single JSON object and all the book data as a child object 

## Current Behavior
Gudenberg.json have no parent object but has every 10 child object as a list

## Environment
Windows 

## Related Issues or PRs
NA

**Comment by vigneshRamanathan3105** [comment]
I will fix this.

I am already working on it.

Assign it to me,

**Comment by neokd** [comment]
You can work on it. I'll keep the PR open

**Comment by vigneshRamanathan3105** [comment]
also assign it to me please

**Comment by vigneshRamanathan3105** [comment]
@neokd storing the data in a json file seems to have a problem.

The file size is getting larger and it is harder to handle in python script.

How about using a database maybe mongodb?

**Comment by neokd** [comment]
For now either u can zip the file, we are looking into different solutions and how to manage the data

**Comment by vigneshRamanathan3105** [comment]
@neokd the problem is not just uploading the data.

I am facing issues while handling large JSON file during web-scrapping.

**Comment by neokd** [comment]
What issue do u get can u send a screenshot

**Comment by vigneshRamanathan3105** [comment]
The script becomes slow as it has to process the data in memory before writing it to the file

**Comment by neokd** [comment]
Yes, that's a general behaviour with scrappers I was later thinking of adding multi threading but have no idea with success rate

**Comment by vigneshRamanathan3105** [comment]
Tried that as well but didn't help.

Just thought of a workaround about saving all the data in a RDBMS.

If needed we can easily export it to CSV

**Comment by neokd** [comment]
You can make a PR or send me the code we can try an alternative way to fix it

**Comment by vigneshRamanathan3105** [comment]
I think we can close this issue. the website is has around 72K books, In the previous pull request around 13K have been scrapped.

I needed I will create separate PR and merge the remaining books.
