### ISSUE TITLE
Add requirements.txt file to ensure everyone is using the same Python env for the development

### ISSUE THREAD

**Issue by js-kalsi** [neokd/DataStorehouse#57]
## Description

- Add `requirements.txt` and update the `README` on how to set up the Python env. 
- This way we will be sure that everyone is using the same version of Python while developing.
- And in the future, this will save us from compatibility-related errors in different Python versions.
- Decide on what Python version we should use as a default.

**Comment by js-kalsi** [comment]
@neokd, let me know if this issue makes sense to you, thanks

**Comment by neokd** [comment]
The requirements.txt is for entire  project or specific, because I was thinking to have a seperate one for Scrapper. You can work on it

**Comment by neokd** [comment]
Thanks for Ur contribution
