### ISSUE TITLE
Github Scrapper. (get_orgs(), get_achievements() )

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#64]
Create a scrapper `get_orgs()` get users organisations from github also create `get_achievements()` get users achieved badge on github

**Comment by Bchass** [comment]
Currently working on this. Users organizations is finished, running into some roadblocks with a users achievements.

**Comment by Bchass** [comment]
Also, do you want these functions to live in `github.py` or completely separate?

**Comment by neokd** [comment]
In GitHub.put
