### ISSUE TITLE
Repo count

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#74]
Create a function in GitHub.py to get the total number of repositories that a user has

**Comment by KBx4** [comment]
> Create a function in GitHub.py to get the total number of repositories that a user has

Hey, just created the function get_total_repositories() in github.py, I have submitted a pull request to merge.

**Comment by KBx4** [comment]
> > Create a function in GitHub.py to get the total number of repositories that a user has
> 
> Hey, just created the function get_total_repositories() in github.py, I have submitted a pull request to merge.

Can you check and authorize my pull request?

**Comment by neokd** [comment]
Thanks for your contribution❤️
