### ISSUE TITLE
Standardise GitHub scrapper output

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#77]
To standardise the GitHub scrapper output for all the function and make a standard function to call the GitHub API.

**Comment by vigneshRamanathan3105** [comment]
@neokd  can you provide more info on this ?

**Comment by neokd** [comment]
To format all the return types to a standard format. Probably as a JSON

**Comment by vigneshRamanathan3105** [comment]
Okay maybe we can create a json with all the function outputs for each user.


And in future if we add new functions we can update the json.

**Comment by neokd** [comment]
@vigneshRamanathan3105 we aren't thinking like that the return types from all the functions to be in a standard format.

**Comment by vigneshRamanathan3105** [comment]
@neokd  Sure once it is finalized let me.
