### ISSUE TITLE
Complete Scrapping of Gutenberg 

### ISSUE THREAD

**Issue by VigneshRamanathan101** [neokd/DataStorehouse#78]
## Description
Currently Gutenberg website has around 72K books. This issue is to scrape all the books

## Expected Behavior
gutenberg_bibliographic_records.json should have around 72 K records 

## Current Behavior
Today gutenberg_bibliographic_records.json has around 13K records

## Possible Solution (optional)
Run Gutenberg scrapper till we scrape all the records

**Comment by vigneshRamanathan3105** [comment]
Any new commers can take up this.

**Comment by neokd** [comment]
What is the issue @vigneshRamanathan3105 ?

**Comment by vigneshRamanathan3105** [comment]
We have no issue @neokd .

we only need to run the scrapper till we scrape all the books. Which might take several hours (due to huge no. of books)

As of now the latest book is [John's Lily](https://gutenberg.org/ebooks/71229)

**Comment by neokd** [comment]
Thanks for your contribution @VigneshRamanathan101 We'll try scrapping more books
