### ISSUE TITLE
Issue with website card layout

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#80]
## Description
Website card layout is not perfect and doesn't adjust based on screen width

## Expected Behavior
Based on view port width adjust the card width

![Screenshot 2023-07-23 at 5 43 03 PM](https://github.com/neokd/DataStorehouse/assets/71772185/9843e06d-610f-4232-9048-859ad20bdc19)

**Comment by Bchass** [comment]
Are you able to provide a readme to run the website locally?

**Comment by neokd** [comment]
You can 
`cd Website`
Then 
`npm i`
And to start the website type
`npm run dev`

**Comment by ujju2000** [comment]
can i work on this issue ?

**Comment by neokd** [comment]
Yes you guys can collaborate and work on the issue

**Comment by Bchass** [comment]
> can i work on this issue ?

Let me know if you come across anything. I worked on it a bit last night, but wasn't able to figure it out yet.

**Comment by Bchass** [comment]
@neokd I fixed this issue: https://github.com/neokd/DataStorehouse/pull/84
