### ISSUE TITLE
Cards disappear/don't show

### ISSUE THREAD

**Issue by Bchass** [neokd/DataStorehouse#83]
## Description

Currently, some cards do not show: 

`x, x(csv)`

`x(csv) will not show.`

## Expected Behavior

Both cards should show.

## Current Behavior

Some cards are not displaying correctly.

## Steps to Reproduce (if applicable)

See below

## Screenshots or Additional Information

https://github.com/neokd/DataStorehouse/assets/34097574/034837d1-2f1c-42b5-b681-8e4afd30fb85

## Environment

Browser tried: FireFox, Chrome, and Safari

## Possible Solution (optional)

Looking into it

## Reproducible Demo (optional)

See `Screenshots or Additional Information`

## Related Issues or PRs

N/A

**Comment by Bchass** [comment]
If you have the dev console open in a browser, the bug will not be present and both cards will show as expected.

**Comment by Bchass** [comment]
This bug appears when only two cards are in a section. If I add another card to Food and Culinary, the bug will no longer be present.

**Comment by neokd** [comment]
@Bchass you can work on it. I'm not able to figure out why the bug occurs.

**Comment by Bchass** [comment]
Haven't come up with anything still. This one is a pain for sure.

**Comment by neokd** [comment]
Yeah, have tried finding the error but still doesn't work accordingly
