### ISSUE TITLE
Create Twitter Scrapper

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#86]
Create a class Twitter or X in scrapper folder to scrape twitter

**Comment by Bchass** [comment]
Few things to think about:
- Do we want to use login creds?
- If we want to bypass login creds, we'll need an API like: https://scrapfly.io but depends on how many calls we want a month
- User profiles or random tweets?

**Comment by neokd** [comment]
Yes, I'm thinking of using two approaches one is with credentials that would be easy but since twitter has a rate limit we can also implement 3rd party APIs.
