### ISSUE TITLE
Get Interview related question and answer (MCQ)

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#88]
Create a scrapper to scrape common interview website like interview bit, gfg ,etc and store it in a JSON format

`
{
  question:"",
  answer:"",
  options:""
}
`
Options can be an array of strings

**Comment by tuhinaww** [comment]
Hey @neokd, I'm interested in working on this issue and developing a web scraper that extracts interview questions. 

Implementation:

- [ ]  I will select target website
- [ ] Develop the scraping script for one website and get it reviewed 
- [ ] Refine the script, implement JSON formatting, and explore MCQ handling
- [ ] Extend the script to other websites
- [ ] Perform thorough testing
- [ ]  Make any necessary adjustments

**Comment by neokd** [comment]
@tuhinaww  you can work on it

**Comment by tuhinaww** [comment]
@neokd thank you!

**Comment by tuhinaww** [comment]
@neokd , Hey I have crated a website scrapper for gfg, and I would like to get it reviewed so I can start with other websites as well.
