### ISSUE TITLE
Any new datasets are accepted 

### ISSUE THREAD

**Issue by neokd** [neokd/DataStorehouse#95]
## Description
New datasets for the repository

**Comment by sukhmani1303** [comment]
kindly assign me this issue!

**Comment by neokd** [comment]
What kind of dataset are you adding @sukhmani1303

**Comment by sukhmani1303** [comment]
I actually have a bunch of datasets like customer churn (10k+ rows) -> got this from a Data Science Assignment Round, Financial Dataset (OrderID, ProductID, Sale-Date, Amount in Sales, Amt Discounted, Region) etc....

Do you need absolutely unique ones or is it okay if Dataset is already available on other platforms?

**Comment by neokd** [comment]
It's okay if we have on other platforms

**Comment by sukhmani1303** [comment]
cool, then I will add multiple datasets 😄

**Comment by neokd** [comment]
Yeah sure, Thanks for your contribution ❤️

**Comment by sukhmani1303** [comment]
@neokd , I directly worked in the main 😶‍🌫️... should i close the pull request & resend or you will be approving it as there are no conflicts 😄

**Comment by neokd** [comment]
I'll directly merge it. Make sure to make a branch from next time.
